localedef -f ISO-8859-1 -i aa_DJ aa_DJ
localedef -f UTF-8 -i aa_ER aa_ER
localedef -f UTF-8 -i aa_ER-Saaho aa_ER-Saaho
localedef -f UTF-8 -i aa_ET aa_ET
localedef -f UTF-8 -i am_ET am_ET
localedef -f UTF-8 -i gez_ER gez_ER
localedef -f UTF-8 -i gez_ET gez_ET
localedef -f UTF-8 -i gez_ER-Abegede gez_ER-Abegede
localedef -f UTF-8 -i gez_ET-Abegede gez_ET-Abegede
localedef -f UTF-8 -i om_ET om_ET
localedef -f ISO-8859-1 -i om_KE om_KE
localedef -f UTF-8 -i sid_ET sid_ET
localedef -f ISO-8859-1 -i so_DJ so_DJ
localedef -f UTF-8 -i so_ET so_ET
localedef -f ISO-8859-1 -i so_KE so_KE
localedef -f ISO-8859-1 -i so_SO so_SO
localedef -f UTF-8 -i ti_ER ti_ER
localedef -f UTF-8 -i ti_ET ti_ET
localedef -f UTF-8 -i tig_ER tig_ER
